[[redirects]]
  from = "https://akulaurila.com/*"
  to = "https://about.akulaurila.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.akulaurila.com/*"
  to = "https://about.akulaurila.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://www.about.akulaurila.com/*"
  to = "https://about.akulaurila.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://akulaurila.netlify.app/*"
  to = "https://about.akulaurila.com/:splat"
  status = 301
  force = true